### ISSUE TITLE
TODO-Liste für eine neue überarbeitete Version

### ISSUE THREAD

**Issue by aeberhard** [FriendsOfREDAXO/xoutputfilter#65]
- [ ] Plugins entfernen und in das Basis-Addon
- [ ] abbrev-Plugin ersatzlos entfernen
- [ ] Funktionen nach Möglichkeit in Klassen überführen
- [ ] UI überarbeiten
- [ ] Dokumentation
  - [ ] Doku-Plugin entfernen
  - [ ] Doku in README
- [ ] Hinweis im Backend "Xoutpufilter ist nicht aktiviert" entfernen
- [ ] vorhandene Issues beachten und evtl. umsetzen
- [ ] .php-cs-fixer.dist.php hinzufügen, Code-Styling
- [ ] Code-Quality mit rexstan

**Comment by skerbis** [comment]
Auf Sorachen verzichten und „nur“ Output-Filter anbieten? Einen Sprachspezialisten gibt es ja schon mit sprog. Ich sehe hier den Schwerpunkt bei Modifikationen im Backend oder Frontend, Eingabekorrekturen oder ähnliches.

**Comment by aeberhard** [comment]
Nein, ich verwende nur den xoutputfilter, darum will ich die Sprachen schon drin lassen.
Abbrev bin ich jetzt auch nicht sicher. Sprog hat jetzt auch abbrevs von daher würde ich das doch auch drin lassen.

**Comment by skerbis** [comment]
Ok
